services:
  db:
    image: ankane/pgvector
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ./migrations/vector-1536.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=vectordb
volumes:
  data: