services:
  db:
    image: ankane/pgvector
    ports:
      - 5433:5432
    volumes:
      - ./migrations/vector-1536.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd